config/routes.rb
SocialNetworking::Application.routes.draw do
  devise_for :users
  
  resources :home do
    member do
      post 'search'
    end
  end
  
  resources :users do
    collection do
      resources :friends 
    end  
  end
  
  resources :posts do
    resources :comments
    resources :likes, :only => :create
  end
  
 

  get "friends/index"

  get "profile/index"
   
  get "comments/index"
   
  put "posts/:post_id/unlike", :to => "likes#unlike", :as => :unlike
  put "/respond", :to => "friends#respond_request", :as => :respond
  post "/add_friend", :to => "friends#add_friend", :as => :add_friend
  post "search/:search_name", :to => "users#search", :as => :search_friends

    root :to => 'home#index'

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!

  def create
    @post = Post.where(:id => params[:post_id]).first
    @comment = @post.comments.new(:user_id => current_user.id, :status => params[:status], :image => params[:image])
    if @comment.save
      flash[:notice] = "Comment created."
    else
      flash[:error] = "Comment not created. Please try again later."
    end  
    @comments = @post.comments
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p> 
  <strong>Commenter:</strong>
  <%= post.user.name %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= post.staus if post.status.present? %>
  <%= post.image if post.image.present? %>
</p>

app/views/comments/_comment_form.html.erb
<%= form_for current_user, :url => new_user_post_comment_path, :html => { :multipart => true} do |f| %>
  
  
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :current_user.name %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  
  <div class="field">
    &nbsp;&nbsp; &nbsp;&nbsp;<%= f.label :Photo %>:
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= form_tag(post_comments_path(post_id), :method => 'post', :multipart => true, :remote => true) do %>    
    <table> 
      <tr>
        <td>
          <div class="field">
            <%= label_tag(:status, "Comment") %>&nbsp;:
            <%= text_field_tag(:status,'', size: 40, placeholder: 'Comment on this post....' ) %>
          </div>
         
          <div class="field">
            <%= label_tag(:image,"attach_picture") %>:
            <%= file_field_tag(:image) %>
          </div>
        </td>
      </tr>
      
      <tr>
        <td colspan='2'>
          <div class="actions">
            <input type="submit" class="btn btn-info btn-sm" value="comment"/>
          </div>
        </td>
      </tr> 
    </table>
  <% end %>
<% end %>

app/views/comments/_preview.html.erb
<% if comments.present? %>
  <% comments.each do |comment| %>
    <div class="container">  
      <div class="col-md-12">
        <div class="col-md-2">
          <%= comment.user.first_name if comment.user.present? %> ->
            <%= comment.status if comment.status.present? %>
            <%= image_tag comment.image, :height => '100', :width => '200' if comment.image.present? %>
        </div>
        
        <div class='col-md-6'> 
          <div class='col-md-3 likes_on_<%= comment.id %>'>
            <%= render :partial => 'likes/like', locals: { :post => comment } %>
          </div>
          <div class='col-md-2'>
            <% if comment.user.id == current_user.id %>
              <%= link_to 'Destroy', post_path(comment), :method => :delete, :confirm => "Click ok if you want to delete" %>
            <% end %>  
          </div>
        </div>  
      </div>  
    </div>  
  <% end %>
<% end %>

app/views/comments/create.js.erb
$(".preview_<%= @post.id %>").html("<%= escape_javascript( render(:partial => 'comments/preview', :locals => { :comments => @comments })) %>");
<% if flash[:error].present? %>
$(".alert-success").hide(500);
$(".alert-warning").html("<%= escape_javascript( flash[:error]) %>").show(500);
<% else %>
$(".alert-warning").hide(500);
$(".alert-success").html("<%= escape_javascript( flash[:notice]) %>").show(500);
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/comments/preview.html.erb
<table>
<% if @comments.present? %>
  <% @comments.each do |comment| %>
    <tr>  
      <td>
        <%= comment.user.name if comment.user.present? %>
      </td>
      <td>
        <%= comment.status if comment.stauts.present? %>
        <%= image_tag comment.image, :height => '100', :width => '200' if comment.status.present? %>
      </td>
    </tr>
  <% end %>
<% end %>
</table>

app/views/comments/show.html.erb
<%= render 'comment' %>