config/routes.rb
SocialNetworking::Application.routes.draw do
  devise_for :users
  
  resources :home do
    member do
      post 'search'
    end
  end
  
  resources :users do
    collection do
      resources :friends 
    end  
  end
  
  resources :posts do
    resources :comments
    resources :likes, :only => :create
  end
  
 

  get "friends/index"

  get "profile/index"
   
  get "comments/index"
   
  put "posts/:post_id/unlike", :to => "likes#unlike", :as => :unlike
  put "/respond", :to => "friends#respond_request", :as => :respond
  post "/add_friend", :to => "friends#add_friend", :as => :add_friend
  post "search/:search_name", :to => "users#search", :as => :search_friends

    root :to => 'home#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
  attr_accessible :friend_with, :request_accepted, :user_id
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  include ApplicationHelper  
  before_filter :authenticate_user!
  before_filter :all_friends, :only => :index
  
  def index
    @friends = User.where("id in (?)", @friend_ids)
  end
  
  def add_friend
    if  current_user.friends.create(:friend_with => params[:friend_id],:request_accepted => false)
      flash[:notice] = "Friend request has been sent."
      redirect_to users_path
    else  
      flash[:error] = "Friend request not sent. Please try again later"
    end
  end
  
  def respond_request
    current_friend_id = Friend.select(:id).where("user_id = ? and friend_with = ?", params[:friend_id], current_user.id)
    if Friend.where("friend_with = ? and user_id = ? and request_accepted = ?",current_user.id, params[:friend_id], true).present?
      Friend.delete(current_friend_id) 
      flash[:alert] = "Friend removed from your list."
    else
      Friend.update(current_friend_id,:request_accepted => "true")
      flash[:notice] = "Friend request accepted."
    end
    redirect_to friends_path
  end
  
  private
  def all_friends
    f1 = current_user.friends.pluck(:friend_with)
    f2 = Friend.where("friend_with = ?", current_user.id).pluck(:user_id)
    @friend_ids = f1 + f2
  end
  
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<%= render 'home/header' %>
</br></br></br></br>
<p id="notice"> <%= notice %> </p>
<h2> List of your friends </h2>
<table class='table table-striped'>
  <tr>
    <th>id</th>
    <th>Name</th>
    <th>Date of birth</th>
    <th>Email</th>
    <th></th>
  </tr>

  <% @friends.each do |friend| %>
    <%= form_for @current_user,:url => respond_path(:friend_id => friend.id ) do |f| %>
      <tr>
        <td><%= friend.id %></td>
        <td><%= friend.first_name + " " + friend.last_name.to_s %></td>
        <td><%= friend.date_of_birth %></td>
        <td><%= friend.email %></td>
        <td>
          <% text = is_friend?(friend)%>
          <div class="actions">
            <%= f.submit value="#{text}", :name => "#{text}" %>
          </div>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/friends/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Date of birth</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @friends.each do |friend| %>
    
      <tr>
        <td><%= friend.id %> </td>
        <td><%= friend.name %></td>
        <td><%= friend.date_of_birth %></td>
        <td><%= friend.email %></td>
        <td>
          <div class="actions">
            <%= f.submit value="Remove Friend" %>
          </div>
        </td>
      </tr>
    
  <% end %>
</table>

<br />


<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %> |
<%= link_to 'back', home_index_path %>