config/routes.rb
SocialNetworking::Application.routes.draw do
  devise_for :users
  
  resources :home do
    member do
      post 'search'
    end
  end
  
  resources :users do
    collection do
      resources :friends 
    end  
  end
  
  resources :posts do
    resources :comments
    resources :likes, :only => :create
  end
  
 

  get "friends/index"

  get "profile/index"
   
  get "comments/index"
   
  put "posts/:post_id/unlike", :to => "likes#unlike", :as => :unlike
  put "/respond", :to => "friends#respond_request", :as => :respond
  post "/add_friend", :to => "friends#add_friend", :as => :add_friend
  post "search/:search_name", :to => "users#search", :as => :search_friends

    root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :customize_name
  
  
  validates :first_name, :presence => true,
                         :format => {:with => /\A[a-zA-Z]+\Z/, :message => "First Name must contain only letters."} 
  
  validates :last_name, :presence => true,
                         :format => {:with => /\A[a-zA-Z]+\Z/, :message => "Last Name must contain only letters."} 
                         
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :date_of_birth, :email, :first_name, :last_name, :password, :password_confirmation          
  
  has_many :likes
  has_many :posts
  has_many :friends, :conditions => {:request_accepted => true}
  has_many :pending_friend_request, :class_name => "Friend", :foreign_key => "user_id", :conditions => {:request_accepted => false }
       
  
  
  def customize_name
    self.first_name = self.first_name.titleize
    self.last_name = self.last_name.titleize
  end
  
  scope :search, ->(search_keyword, friend_ids){
    User.where("id NOT IN (?) AND first_name ilike ? OR last_name ilike ? ", friend_ids, "%#{search_keyword}%", "%#{search_keyword}%")
  }
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :add_friends, :only => [:index, :search]
  
  def index
    
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html      
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to wall_path, :notice => 'User was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def search
    
    @found = User.search("#{params[:search_name]}", @friend_ids) 
    if @found.present?
    respond_to do |format|
      format.js
    end  
    else
      flash.now[:notice] = "User not found"
      @found = @users
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  
  def add_friends
    f1 = current_user.friends.pluck(:friend_with)
    f2 = current_user.pending_friend_request.pluck(:friend_with)
    @friend_ids = f1 + f2
    @friend_ids << current_user.id
    @users = User.where("id NOT IN (?)", @friend_ids)
  end
 
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  

<div class="field">
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <p id="notice"><%= notice %></p>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_friends.html.erb
<table class='table table-striped'>  
    <tr>
      <th>id  </th>
      <th>Name</th>
      <th>Date of birth</th>
      <th>Email</th>
      <th></th>
    </tr>
  <% users.each do |user| %>
    <% if is_not_requested?(user) %>
      <tr>
          <td><%= user.id %> </td>
          <td><%= user.first_name + " " + user.last_name.to_s %></td>
          <td><%= user.date_of_birth %></td>
          <td><%= user.email %></td>
          <td>
           <%= form_for @current_user,:url => add_friend_path(:friend_id => user.id), :method => :post do |f| %>
              <div class="actions">
                <%= f.submit value="Add Friend" %>
              </div>
            <% end %>
          </td>
        </tr>
     
    <% end %>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %>|
<%= link_to 'Logout', logout_login_index_path %>

app/views/users/index.html.erb
<%= render 'home/header' %>
</br></br></br></br>
<p id="notice"><%= notice %></p>
    
    <%= label_tag(:search) %>
    <%= text_field_tag(:search,'',size: 20, placeholder: 'Search your friend', :id => 'keyword') %>
    <button id='search' > Search </button>
    
    
<h2>People you may know.</h2>

  
<div id="searched_items">
  <%= render :partial => 'friends', :locals => { :users => @users } %>
</div>


<script type="text/javascript" charset="UTF-8">  
  if($('#keyword').val() ==  "") {
    $('#search').attr('disabled', true);
  }
  $(document).on("click", "#search", function(){
    var search_keyword = $("#keyword").val();
    search_method(search_keyword)
  });
  
  function search_method(keyword){
    $.ajax({
      url: "/search/"+keyword, type: "POST"
    });
  };
  
  $(document).on("keyup", "#keyword", function(e){
    if( e.keyCode == 13 || ($.trim($("#keyword").val())).length >= 3 ){
      var search_keyword = $("#keyword").val();
      search_method(search_keyword)
    }
    else{    
      $("#searched_items").html("<%= escape_javascript( render(:partial => 'users/friends', :locals => { :users => @users }))%>");
    }
  });
</script>

app/views/users/new.html.erb
<p id="notice"> <%= notice %> </p>
<h1>New user</h1>

<%= render 'form' %>

app/views/users/search.js.erb
$("#searched_items").html("<%= escape_javascript( render(:partial => 'users/friends', :locals => { :users => @found }))%>");
$("#notice").html("<%= escape_javascript( flash[:notice] )%>");