config/routes.rb
SocialNetworking::Application.routes.draw do
  devise_for :users
  
  resources :home do
    member do
      post 'search'
    end
  end
  
  resources :users do
    collection do
      resources :friends 
    end  
  end
  
  resources :posts do
    resources :comments
    resources :likes, :only => :create
  end
  
 

  get "friends/index"

  get "profile/index"
   
  get "comments/index"
   
  put "posts/:post_id/unlike", :to => "likes#unlike", :as => :unlike
  put "/respond", :to => "friends#respond_request", :as => :respond
  post "/add_friend", :to => "friends#add_friend", :as => :add_friend
  post "search/:search_name", :to => "users#search", :as => :search_friends

    root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user! 
  before_filter :all_friends_posts, :only => [:index, :search]
 
  def index
    @posts_to_show = @posts
  end
  
  def create
  end
  
  def show
  end 
  
  def new
  end
  
  def search
    if params[:id].to_i == 0
      @posts_to_show = @posts
    elsif params[:id].to_i == 1
      @posts_to_show = Post.all_status(@friend_ids).where(:image => nil)
    else
      @posts_to_show = Post.all_images(@friend_ids)
    end
  end
  
  
  private 
  
  def all_friends_posts 
    f1 = current_user.friends.where("request_accepted = ?", true).pluck(:friend_with)
    f2 = Friend.where("friend_with = ? and request_accepted = ?", current_user.id, true).pluck(:user_id)
    @friend_ids = f1 + f2 << current_user.id
    @posts = Post.where("user_id in (?) and is_comment = ?",@friend_ids, false).order("created_at DESC")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_comment_form.html.erb
<%= form_for(([current_user, :url => new_user_post_comment_path), :html => { :multipart => true, :method => "post"}) do |f| %>
  
  
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :current_user.name %>
  </div>
  
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  
  <div class="field">
    &nbsp;&nbsp; &nbsp;&nbsp;<%= f.label :Photo %>:
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/home/_flash.html.erb
  
  <div class="alert-success">
    <p id="notice"><%= flash[:notice] %></p>
  </div>
  
  <div class="alert-warning"> 
    <p id="flash-error"><%= flash[:error] %></p>
  </div>

  <div class="alert-danger"> 
    <p id="flash-alert"><%= flash[:alert] %>
    </p>
  </div>

app/views/home/_footer.html.erb
<div id="footer" class="container">
    <nav class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="navbar-inner navbar-content-center">
           <a href="http://www.grepruby.com" target='blank'> <div class="btn btn-danger"> GrepRuby Webtech Pvt. Ltd </div> </a> |
           <%= link_to 'Contact Us' %> | <%= link_to 'About Us' %> | <%= link_to 'Feedback' %>
        </div>
    </nav>
</div>

app/views/home/_form.html.erb
<div class="container">
  <div class="row ">
    <div class="form-inline" role="form">
      <%= form_for(current_user.posts.build, :html => {:multipart => true, :method => "post"}) do |f| %>
        <div class="row">
          <div class="span3 offset3 well">
            <div class="form-group">
              <h3>Create Post from here....&nbsp;&nbsp;</h3>
            </div> 
            <div class="form-group">
              <div class="field">
                <%= f.label :Status %>&nbsp;:</br>
                <%= f.text_field :status, autofocus: true %>
              </div>
            </div>
            <div class="form-group">
              <div class="field">
                &nbsp;&nbsp;<%= f.label :Photo %>&nbsp;:
                <%= f.file_field :image %>
              </div>
            </div>
            <div class="form-group">
              <div class="actions">
                <input type="submit" class="btn btn-success btn-sm" value="create post"/>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<div class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <ul class="navbar-brand">
        Welcome <%= current_user.first_name + " " + current_user.last_name.to_s %>
      </ul>    
      <ul class="nav navbar-nav pull-right">
        <li><i class=""></i><%= link_to "Home", home_index_path %></li>       
        <li><%= link_to "Find Friends", users_path %></li>
        <li><%= link_to "View Friends", friends_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div>
  </div>
</div>   

app/views/home/_post.html.erb
<table >
  <% @posts.each do |post|%>
    <tr height=50px>
      <td>
        <%= post.user.name %> -->
      </td>
      <td>
        <%= post.status if post.status.present? %></br>
        <%= image_tag post.image, :height => '300', :width => '400' if post.image.present? %>
      </td>
      <td>
        <% if post.user.name == current_user.name %>
          <%= link_to 'Destroy', [post.user, post], :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>    
  <% end %>
</table>

app/views/home/index.html.erb
<body>
  <% if user_signed_in? %>
    
    </br></br></br></br>
    
    <%= render partial: 'flash', :locals => { flash: flash } %>
      
    <%= render 'header'%>
    
    <%= render 'form' %>
    
    <div class="container">
      <div class='row-fluid'>  
        <div class="span6 pull-right">
          <%= label_tag(:search_posts_status_or_images) %> <br/ >          
          <%= select_tag :posts, options_for_select([["All", 0], ["Only Status", 1], ["Only Pics", 2]]), :id => "search_posts" %>
          <button id='search' > Go </button>
        </div>
      </div>  
    </div>  
    
    
    
    <div id="search_post">
      <%= render partial: 'posts/post' %>
    </div>
    
    <%= render 'footer' %>
    
  <% end %>
</body>

<script type="text/javascript" charset="UTF-8">
  $(document).on("click", "#search", function(){
    var id = $("#search_posts").val();
    $.ajax({
      url: "/home/"+id+"/search", type: "POST"
    });
  });
</script>

app/views/home/new.html.erb
  <render 'form'>
<h2>Current haapenings...</h2>

app/views/home/search.js.erb
$("#search_post").html("<%= escape_javascript( render(:partial => 'posts/post'))%>");

app/views/home/show.html.erb
<p id="notice"> <%= notice %> </p>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
<%= if user_signed_in? %>
  <h2>Current haapenings...</h2>


<%= else %>

<h1> welcome Social Networking Site!</h1>
<%= link_to "Sign In", new_user_session_path, :method => :get %>
<%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>